version: "2"

linters:
  default: standard
  enable:
    - govet
    - errcheck
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports

run:
  concurrency: 4
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
